---
title: "Tutorial"
author: "Michael Rustler"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
```{r eval = TRUE, echo=FALSE, warning=FALSE, message=FALSE}


secret_paths <- c("secret.csv")
exist_secret_paths <- file.exists(secret_paths)
secret_path <- NA

if (!identical(Sys.getenv("TRAVIS"), "true")) {
  
if(any(exist_secret_paths)) {
  secret_path <- secret_paths[exist_secret_paths]
  
Sys.setenv("ORCID_TOKEN" = as.character(read.csv(secret_path,
                                                 stringsAsFactors = FALSE)))
}
}
```
# 1 Install R Packages

First you need to install the following required R packages:

```{r, eval = FALSE}
installed_packages <- rownames(installed.packages())

### For installing an R package from Github
if(!"devtools" %in% installed_packages) {
  install.packages("devtools", repos = "https://cloud.r-project.org")
}
### R package for checking ORCID use at KWB
if(!"kwb.orcid" %in% installed_packages) {
  devtools::install_github("KWB-R/kwb.orcid")
}

```

# 2 Check ORCID Use

## 2.1 Authenticate 

Either check in interactively with `rorcid::orcid_auth()` (opens) or provide a valid 
`orcid_token` 

```{r, echo=TRUE,eval = FALSE}
### If no "orcid_token" is specified in: 
### Sys.setenv("orcid_token" = "my_secret_orcid_token")
### it opens up the web browser for login to ORCID in order to create a 
### authentication token
rorcid::orcid_auth()

### After finishing this step the token is printed to the console, e.g.
> "Bearer my_secret_orcid_token"



### To make this token available in the next R session make sure to set the
### token via Sys.setenv() as shown below
Sys.setenv("orcid_token" = "my_secret_orcid_token")


```

```{r echo = FALSE}
if(!is.na(secret_path)){
  knitr::opts_chunk$set(eval=TRUE, message=FALSE, echo=TRUE)
} else {
 knitr::opts_chunk$set(eval=FALSE, message=FALSE, echo=TRUE)
}
```


## 2.2 Get names and url for all ORCIDs 
```{r}

### Data frame with ORCIDs currently used at KWB
orcids <- kwb.orcid::get_kwb_orcids()

orcids

authors <- kwb.orcid::get_author_meta_for_orcids(orcids)
```

```{r, echo = FALSE}
knitr::kable(authors)
```

## 2.3 Get publications for all ORCIDs 
```{r}
publications <- kwb.orcid::create_publications_df_for_orcids(orcids)
head(publications)
```

```{r, echo = FALSE}
knitr::kable(publications)
```

<!-- ## 2.4 Unknown status -->
<!-- ```{r} -->

<!-- researchers <- c("Remy, Christian",  -->
<!--                   "Kraus, Fabian",  -->
<!--                   "Menz, Christian",  -->
<!--                   "Stapf, Michael",  -->
<!--                   "Kleyböcker, Anne",  -->
<!--                   "Loderer, Christian") -->

<!-- researchers_list <- try(lapply(researchers, -->
<!-- function(x) { -->
<!--   splitted_names <- strsplit(x, ", ")[[1]] -->
<!--   familyname <- splitted_names[1] -->
<!--   givenname <- splitted_names[2] -->
<!--   rorcid::orcid_search(givenname, familyname) -->
<!-- })) -->
<!-- ``` -->

<!-- ## 2.5 Get DOIS for all publications -->

<!-- ```{r} -->
<!-- publication_dois_df <- data.table::rbindlist(publications$`external-ids.external-id`) -->
<!-- publications_dois <- publication_dois_df$`external-id-value`[publication_dois_df$`external-id-type`=="doi"] -->
<!-- doi_status <- rorcid::check_dois(publications_dois) -->
<!-- ### Check if all DOIs are "good" -->
<!-- sapply(doi_status, length) -->

<!-- try(expr = lapply(doi_status$good, function(x) { -->
<!--   #print(sprintf("DOI: %s", doi)) -->
<!--   knitcitations::citep(x) -->
<!-- }),  silent = FALSE) -->
<!-- ``` -->

<!-- ## Export all citations in .bibtex -->

