#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("extract_orcid_from_path() works", {

  expect_error(
    kwb.orcid:::extract_orcid_from_path()
    # argument "path" is missing, with no default
  )

})

